server.port: 8080

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/mail-client
        username: postgres
        password: postgres
jpa:
    hibernate:
        ddl-auto: update